swagger: "2.0"
info:
  description: "this is the documentation of Argent-Bank Api in the Phase 2 : the transactions"
  version: "1.0.0"
  title: "Argent-Bank API documentation"
  termsOfService: "http://swagger.io/terms/"
     
host: "localhost:3000"
basePath: "/api-docs"
schemes:
  - https
  - http
paths:
  /user/{accountId}:
    get:
      tags:
        - User account details
      summary: user's transactions
      description: show all user's transactions
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account user
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: user transactions showed Successfully
          schema:
            $ref: '#/definitions/Account-Response'
        '400':
          description: Either `token` or `accountId` are required.
        '500':
          description: Internal Server Error
  /user/{accountId}/{transactionId}:
    get:
      tags:
        - User transaction details
      summary: transaction details
      description: retrieve specific informations of the transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account user
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User transaction details retrieved Successfully
          schema:
            $ref: '#/definitions/Transaction-Response'
        '400':
          description:  One of them `token`, `transactionId` or `accountId` are required.
        '500':
          description: Internal Server Error
  /user/{accountId}/{transactionId}/category:
    post:
      security:
        - Bearer: []
      tags:
        - User transaction details
      summary: Modify transaction details
      description: Updating specific transactions informations about category
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account user
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: transaction informations about category successfully updated
          schema:
            $ref: '#/definitions/Transaction-Updating-Response'
        '400':
          description: One of them `token`, `transactionId` or `accountId` are required.
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - User transaction details
      summary: retrieve transaction details
      description: retrieve specific transactions informations
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account user
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: transaction informations successfully retrieved
          schema:
            $ref: '#/definitions/Transaction-Retrieve-Details-Response'
        '400':
          description: One of them `token`, `transactionId` or `accountId` are required.
        '500':
          description: Internal Server Error
  /user/{accountId}/{transactionId}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - User transaction details
      summary: Create transaction details
      description: Add Notes to the transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account user
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: transaction notes successfully updated
          schema:
            $ref: '#/definitions/Transaction-Updating-Response'
        '400':
          description: One of them `token`, `transactionId` or `accountId` are required.
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - User transaction details
      summary: retrieve transaction details
      description: retrieve specific transaction information
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of the account user
          required: true
          type: integer
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: transaction informations successfully retrieved
          schema:
            $ref: '#/definitions/Transaction-Retrieve-Details-Response'
        '400':
          description: One of them `token`, `transactionId` or `accountId` are required.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      transactionId:
        type: number
        description: transaction unique id
      date:
        type: string
        description: date of transaction
      description:
        type: string
        description: description of transaction
      amount:
        type: number
        description: amount of transaction
      balance:
        type: number
        description: balance of the account after transaction
  TransactionDetails:
    type: object
    properties:
      transactionId:
        type: number
        description: transaction unique id
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: category of the transaction
      notes:
        type: string
        description: any relevant note user want to add
  Account:
    type: object
    properties:
      accountId:
        type: number
        description: Id of the user account
      balance:
        type: number
        description: balance of the owner account
      currency:
        type: string
        description: currency
  Account-Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transactions retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Account'
  Transaction-Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction retrieved succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction-Updating-Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: transaction updated succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/TransactionDetails'
  Transaction-Retrieve-Details-Response:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction updated succesfully
      body:
        type: array
        items:
          $ref: '#/definitions/TransactionDetails'